### ISSUE TITLE
Widget test: can not execute test with widget contain GetScaffold widget

### ISSUE THREAD

**Issue by ahnkiot123a** [asadbaidar/get_smart#3]
## Description
Widget test get an error when function under test contain GetScaffold widget <br>
```sh
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building ThemeBuilder(dirty, dependencies:
[_LocalizationsScope-[GlobalKey#d7b21], _InheritedTheme]):
Null check operator used on a null value

The relevant error-causing widget was:
  ThemeBuilder
  ThemeBuilder:file:///flutter/.pub-cache/hosted/pub.dartlang.org/get_smart-0.1.4+8/lib/src/widgets/button.dart:1225:7

When the exception was thrown, this was the stack:
#0      GetInterfaceX.localization (package:get_smart/src/utils/get_interface.dart:65:77)
#1      GetButton.back.<anonymous closure> (package:get_smart/src/widgets/button.dart:1234:23)
#2      ThemeBuilder.build (package:get_smart/src/widgets/widgets.dart:842:16)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4876:49)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4787:5)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
...     Normal element mounting (10 frames)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#18     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#19     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (40 frames)
#59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#60     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#61     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (142 frames)
#203    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#204    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#205    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (23 frames)
#228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#229    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6350:36)
#230    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6362:32)
...     Normal element mounting (7 frames)
#237    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#238    Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
#239    _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:135:18)
#240    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
#241    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:153:12)
#242    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2025:59)
#243    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#244    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2025:14)
#245    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:227:7)
#246    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:316:5)
#247    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#248    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
#249    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1003:7)
#250    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
#251    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#252    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#253    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#254    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#255    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#256    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#257    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#258    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#259    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#260    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#261    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#262    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#263    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#264    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#265    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#266    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#267    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#268    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#269    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#270    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#271    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#272    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#273    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#274    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#275    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#276    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#277    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#278    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#279    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#280    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#281    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#282    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#283    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#284    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#285    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#286    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#287    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#288    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#289    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#290    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#291    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#292    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#293    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#294    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#295    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#296    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3462:13)
#297    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#298    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#299    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#300    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:749:15)
#301    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#302    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#303    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#304    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#305    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#306    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#307    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#308    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#309    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#310    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#311    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#312    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#313    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#314    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#315    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#316    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#317    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#318    RenderObject.layout (package:flutter/src/rendering/object.dart:1915:7)
#319    RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#320    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1757:7)
#321    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#322    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1186:23)
#323    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#324    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#325    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#326    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1050:9)
#329    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#330    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1037:27)
#331    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:548:22)
#334    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#335    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:545:27)
#336    main.<anonymous closure>.<anonymous closure> (file://widget_test.dart:49:20)
#337    main.<anonymous closure>.<anonymous closure> (file://widget_test.dart:46:38)
#338    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
```

## Code example
The example of code contain GetScaffold widget
```sh
Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        return false;
      },
      child: GetScaffold(
        appBarHidden: true,
        toolbarsHidden: true,
        child: SafeArea(
          child: Container(),
        ),
      ),
    );
  }
```

The example code for a widget test:
```sh
testWidgets('build widget test', (WidgetTester tester) async {
  HomeView homeView = HomeView();
  await tester.pumpWidget(
    MaterialApp(
        home: Material(
      child: homeView.build(mockBuildContext),
    )),
  );
});
```

**Comment by ahnkiot123a** [comment]
I use GetMaterialApp instead of MaterialApp in test widget, it fixed this error.

**Comment by ahnkiot123a** [comment]
I use GetMaterialApp instead of MaterialApp in the widget test, it fixed this error.

**Comment by asadbaidar** [comment]
> I use GetMaterialApp instead of MaterialApp in the widget test, it fixed this error.

sorry @ahnkiot123a I couldn’t respond early. good to know that you found the solution. keep up the good work. 👍🏻
